feat: test cov

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -32,10 +32,6 @@ jobs:
 
           echo "$SIX_LABORS_LIC" > ./Messaging.Application/Credentials/sixlabors.lic
 
-      - name: Build
-        run: dotnet build --configuration Release --no-restore
-        
-
       - name: Install dotnet-coverage
         run: dotnet tool install --global dotnet-coverage
       
@@ -57,13 +53,18 @@ jobs:
           recreate: true
           path: code-coverage-results.md
       - name: Generate Coverage Badge Image
-        uses: cicirello/jacoco-badge-generator@v2
-        with:
-                    # Pass your cobertura xml file here
-          coverage-reports: solution_coverage.xml
-          badges-directory: .github/badges
-          generate-coverage-badge: true
-          coverage-label: 'coverage'
+        run: |
+        # Create the directory if it doesn't exist
+        mkdir -p .github/badges
+        
+        # Extract the badge URL from the generated markdown and download the SVG
+        BADGE_URL=$(grep -oE 'https://img.shields.io/[^)]+' code-coverage-results.md | head -n 1)
+        if [ -n "$BADGE_URL" ]; then
+          curl -s -o .github/badges/coverage.svg "$BADGE_URL"
+        else
+          echo "Could not find badge URL in markdown report."
+          exit 1
+        fi
             
       - name: Commit Badge Image
         run: |
